export const initalConfig = {
  Button: {
    text: 'Button Text',
    bgcolor: 'blue',
    color: 'white',
    outline: 'none',
    border: 'none',
    borderRadius: '4px',
    padding: '10px 20px',
    margin: '5px',
    transition: 'background-color 0.3s',
    disabled: false,
    cursor: 'pointer',
    bgcolorHover: 'blue',
    disabledElevation: false,
    fontWeight: 'normal',
    fontSize: '16px',
  },
  Card: {
    variant: 'elevated',
    bgcolor: 'red',
    color: 'white',
    outline: 'none',
    border: 'none',
    borderRadius: '4px',
    fontWeight: 'normal',
    fontSize: '16px',
    padding: '16px',
    margin: '16px',
    display: 'block',
    title: 'Card Title',
    subheader: 'Card Subheader',
    footer: 'Footer',
  },
};
